// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChoicesJsController from "./choices_js_controller"
application.register("choices-js", ChoicesJsController)

import FormMapController from "./form_map_controller"
application.register("form-map", FormMapController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import MarkerController from "./marker_controller"
application.register("marker", MarkerController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PagesController from "./pages_controller"
application.register("pages", PagesController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
